### ISSUE TITLE
Trouble installing on macOS mojave

### ISSUE THREAD

**Issue by JKatsenelinboigen** [da2x/fluxfonts#11]
Thank you for the reply!
"make" worked, but the 2nd command gives a new error.

> /usr/bin/install -d /usr/local/share/doc/fluxfonts
> /usr/bin/install -S AUTHORS COPYING README /usr/local/share/doc/fluxfonts
> /usr/bin/install -d /usr/local/bin
> /usr/bin/install -S fluxfontd /usr/local/bin
> make: * No rule to make target `[install-daemon]'.  Stop.

_Originally posted by @JKatsenelinboigen in https://github.com/da2x/fluxfonts/issues/10#issuecomment-521310391_

**Comment by da2x** [comment]
Does `make install install-launchd` work?

**Comment by JKatsenelinboigen** [comment]
> /usr/bin/install -d /usr/local/share/doc/fluxfonts
> /usr/bin/install -S AUTHORS COPYING README /usr/local/share/doc/fluxfonts
> /usr/bin/install -d /usr/local/bin
> /usr/bin/install -S fluxfontd /usr/local/bin
> rm /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons/fluxfonts.plist
> rm: /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons/fluxfonts.plist: No such file or directory
> make: [configure-launchd] Error 1 (ignored)
> /usr/bin/install -d /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons
> /usr/bin/defaults write /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons/fluxfonts.plist RunAtLoad -boolean TRUE
> /usr/bin/defaults write /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons/fluxfonts.plist Label -string no.priv.daniel.fluxfonts
> /usr/bin/defaults write /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons/fluxfonts.plist ProgramArguments -array-add /usr/local/bin/fluxfontd
> /usr/bin/install -d /Library/LaunchDaemons
> /usr/bin/install /private/var/tmp/fluxfonts.dist/dest_root/Library/LaunchDaemons/fluxfonts.plist /Library/LaunchDaemons
> /bin/launchctl load /Library/LaunchDaemons/fluxfonts.plist

One error that was ignored, but it still doesnt work according to the two sites in your blog post.

**Comment by JKatsenelinboigen** [comment]
Any ideas?

**Comment by da2x** [comment]
> One error that was ignored, but it still doesnt work according to the two sites in your blog post.

Those sites now use a dictionary iteration to check a lit of known fonts. Browsers began blocking font enumeration with the deprecation of Flash Player. It's back with the new Font Enumeration API (only available in Chrome). Fluxfonts still protects against local apps enumerating fonts. It'll also protect against the Font Enumeration API.

**Comment by da2x** [comment]
> Is there a (updated) summary/table somewhere that states which browsers have this API implemented?

Usually the answer to that is CanIUse, but it doesn’t yet have the feature. It’s only implemented in Chromium at the moment. So, Edge, Opera, Chrome, others. Some, like Vivaldi and Brave, might disable it later.

> Is there a statement/notice from Mozilla's side somewhere, if (or if not) they're going to implement it too at some point in Firefox?

https://tinyurl.com/mozfontenum and https://lists.webkit.org/pipermail/webkit-dev/2022-April/032178.html
